//some cool subreddits, add more here if u want
let randomsubredditGet = [
    "pussy",
    "PussyWedgie",
    "PussyFlashing",
    "gonewild",
    "RealGirls",
    "BustyPetite",
    "PetiteGoneWild",
    "cumsluts",
    "LegalTeens",
    "AsiansGoneWild",
    "nsfw_gifs",
    "tiktokthots",
    "rule34",
    "GirlsFinishingTheJob",
    "Amateur",
    "BiggerThanYouThought",
    "hentai",
    "porninfifteenseconds",
    "pawg",
    "LipsThatGrip",
    "ass",
    "Boobies",
    "nsfwcosplay",
    "girlsinyogapants",
    "curvy",
    "workgonewild",
    "AsianHotties",
    "bigasses",
    "gonewildcurvy",
    "asstastic",
    "thick",
    "GirlswithGlasses",
    "quiver",
    "whenitgoesin",
    "redheads",
    "WouldYouFuckMyWife",
    "fitgirls",
    "NSFWverifiedamateurs",
    "Hotchickswithtattoos",
    "theratio",
    "paag",
    "boobs",
    "facedownassup",
    "altgonewild",
    "tightdresses",
    "gonewildcouples",
    "Cuckold",
    "asshole",
    "bdsm",
    "bimbofetish",
    "LabiaGW",
    "AsianNSFW",
    "rileyreid",
    "DegradingHoles",
    "booty",
    "slutwife",
    "iwanttobeher",
    "Ifyouhadtopickone",
    "realmoms",
    "Breeding",
    "Nipples",
    "booty_queens",
    "BBW",
    "amazingtits",
    "DadWouldBeProud",
    "bikinis",
    "EngorgedVeinyBreasts",
    "HotMoms",
    "WomenBendingOver",
    "bigareolas",
    "feet",
    "NSFW_Social",
    "CumHentai",
    "slightcellulite",
    "hentaicaptions"
]

function getRandomSubreddit() {
    const listedR = Math.floor(Math.random() * randomsubredditGet.length);
    return randomsubredditGet[listedR];
}

module.exports = getRandomSubreddit;